### ISSUE TITLE
Enhance "Filter Notes by Keywords" and English Language Support

### ISSUE THREAD

**Issue by TheNomadInOrbit** [Misuzu2027/syplugin-misuzu-custom#1]
The "Filter Notes by Keywords" feature currently does not support case-insensitive searches, which limits its usability. Additionally, it does not search within sub-documents inside a notebook. Also I would request you to please add English language support.

Steps to Reproduce:
- Create a notebook named "Dev".
- Attempt to search using the keyword "dev".
- Observe that the search does not return the expected results.
- Attempt to search for keywords within sub-documents of the notebook.

![image](https://github.com/user-attachments/assets/89ed1e7c-dd96-44bd-88ef-49c9c0e5b819)

![image](https://github.com/user-attachments/assets/0b44a2ed-e705-4b57-bb16-f569ea3e6169)

Expected Behavior:
- The search should be case-insensitive, returning results for both "Dev" and "dev".
- The search should include results from sub-documents within the notebook.

Actual Behavior:
- The search is case-sensitive, only returning results for the exact case.
- The search does not include sub-documents.

Proposed Solution:
- Implement case-insensitive search functionality.
- Extend the search to include sub-documents within notebooks.

**Comment by Misuzu2027** [comment]
Great suggestions! Both of these features can be implemented. 

However, I have a question regarding extending the search range. If sub-documents are matched, should we hide the documents under that notebook that do not match? 

The benefit of hiding them is that it allows for quicker navigation when the list is long. The downside is that it makes development more challenging, as expanding and collapsing the directory would dynamically refresh the document list.

**Comment by Misuzu2027** [comment]
v0.0.3 has been updated:

* Document tree query now ignores keyword case sensitivity
* Supports matching document names under notebooks (requires enabling in settings)

The multilingual English version will be added when time allows in the future.

**Comment by TheNomadInOrbit** [comment]
> 
> However, I have a question regarding extending the search range. If sub-documents are matched, should we hide the documents under that notebook that do not match?
> 

Yes, it should hide the documents under that notebook that do not match; this would be great but also bit challenging as well. See what you can do about this; if it's possible, that would be great.

Also, please support English in future updates. Thanks! 🙏

**Comment by Misuzu2027** [comment]
v0.0.4 Updated

**Comment by TheNomadInOrbit** [comment]
Thank you for the update. I appreciate that.

I just have one request: could you please improve the search so that once it finds a match inside the notebook, it automatically display subnotes? currently I have to click on the arrow to show them manually.

https://github.com/user-attachments/assets/4a2a42ba-929a-4d1a-9c97-29e507d8d30d

**Comment by Misuzu2027** [comment]
Thank you for the suggestion.

However, this feature is currently difficult to implement because the official API does not provide an interface for locating a specific document in the document tree. Therefore, we are unable to update this feature for now.

**Comment by Misuzu2027** [comment]
If you frequently search for documents and don't mind the document structure, you might consider using the Document Search plugin. It includes a "Flat Document Tree Dock" feature that allows you to quickly locate the desired document and supports full-text search within documents.
