### ISSUE TITLE
请问这个插件对思源的版本有要求吗？

### ISSUE THREAD

**Issue by LEDZB** [Misuzu2027/syplugin-misuzu-custom#3]
（1）我直接在Github拉源代码，解压，放置在我工作目录的pulgin目录下
（2）在集市中可以看到此插件，但无法对齐设置，请问是为何呢
![Snipaste_2024-11-26_09-52-37](https://github.com/user-attachments/assets/ddd9b7e5-db97-40d6-9a8c-ff057cdd9e9d)

**Comment by Misuzu2027** [comment]
代码块相关的功能需要升级到 3.1.5 之后。其他功能对版本没有要求。

如果是直接下载源码解压的话，确实不行，因为源码是 ts ，需要编译成 js 才能被插件系统识别执行。有两个方法
1. 安装 nodejs 和 pnpm ，进入源码根目录依次执行 `pnpm i`  , `pnpm build` ，把 dist 中的源码复制到插件根目录中。
2. 直接下载 https://github.com/Misuzu2027/syplugin-misuzu-custom/releases 中的 `package.zip`，里面是已经编译好的代码，解压后直接复制到插件目录即可。

两个方法都需要注意，存放该插件代码的文件夹名称必须是：`syplugin-misuzu-custom`

**Comment by LEDZB** [comment]
> 代码块相关的功能需要升级到 3.1.5 之后。其他功能对版本没有要求。
> 
> 如果是直接下载源码解压的话，确实不行，因为源码是 ts ，需要编译成 js 才能被插件系统识别执行。有两个方法
> 
> 1. 安装 nodejs 和 pnpm ，进入源码根目录依次执行 `pnpm i`  , `pnpm build` ，把 dist 中的源码复制到插件根目录中。
> 2. 直接下载 https://github.com/Misuzu2027/syplugin-misuzu-custom/releases 中的 `package.zip`，里面是已经编译好的代码，解压后直接复制到插件目录即可。
> 
> 两个方法都需要注意，存放该插件代码的文件夹名称必须是：`syplugin-misuzu-custom`

好的，刚验证这个方法2 可以解决问题
